### ISSUE TITLE
Blog data migration doesn't work if upgrading from version 0.5.0 to 0.6.2

### ISSUE THREAD

**Issue by danra** [nephila/djangocms-blog#172]
The problem is in the migration file 0010_auto_20150923_1151.py: The added fields must have null=True. While this is fixed in the subsequent 0011_auto_20151024_1809.py migration, this isn't good enough, since django expects the database to be in a consistent state after each migration.

Without fixing this, attempting to migrate a db with already-existing data results in the following exception.

Running migrations:
  Rendering model states... DONE
  Applying djangocms_blog.0008_auto_20150814_0831... OK
  Applying djangocms_blog.0009_latestpostsplugin_tags_new... OK
  Applying djangocms_blog.0010_auto_20150923_1151...Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dan/dev/soundradix/website/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/dan/dev/soundradix/website/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dan/dev/soundradix/website/venv/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/dan/dev/soundradix/website/venv/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/Users/dan/dev/soundradix/website/venv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/Users/dan/dev/soundradix/website/venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/Users/dan/dev/soundradix/website/venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/dan/dev/soundradix/website/venv/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/dan/dev/soundradix/website/venv/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 62, in database_forwards
    field,
  File "/Users/dan/dev/soundradix/website/venv/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 398, in add_field
    self.execute(sql, params)
  File "/Users/dan/dev/soundradix/website/venv/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/Users/dan/dev/soundradix/website/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/dan/dev/soundradix/website/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/dan/dev/soundradix/website/venv/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/dan/dev/soundradix/website/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: column "app_config_id" contains null values

**Comment by danra** [comment]
Created pull request https://github.com/nephila/djangocms-blog/pull/173
