### ISSUE TITLE
On upgrading: column "app_config_id" contains null values

### ISSUE THREAD

**Issue by Zowie** [nephila/djangocms-blog#178]
When trying to upgrade from Django-1.7 and Djangocms-blog 0.5.0 to Django 1.8.7 and Djangocms-blog 0.6.2, I get the following migration issue:

```
Applying djangocms_blog.0010_auto_20150923_1151...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/zowielangdon/.virtualenvs/proj/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/zowielangdon/.virtualenvs/proj/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/zowielangdon/.virtualenvs/proj/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/zowielangdon/.virtualenvs/proj/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/zowielangdon/.virtualenvs/proj/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/Users/zowielangdon/.virtualenvs/proj/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/Users/zowielangdon/.virtualenvs/proj/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/zowielangdon/.virtualenvs/proj/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/zowielangdon/.virtualenvs/proj/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 62, in database_forwards
    field,
  File "/Users/zowielangdon/.virtualenvs/proj/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 398, in add_field
    self.execute(sql, params)
  File "/Users/zowielangdon/.virtualenvs/proj/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/Users/zowielangdon/.virtualenvs/proj/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/zowielangdon/.virtualenvs/proj/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/zowielangdon/.virtualenvs/proj/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/zowielangdon/.virtualenvs/proj/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: column "app_config_id" contains null values
```

```
aldryn-apphooks-config==0.2.6
aldryn-boilerplates==0.7.3
aldryn-common==1.0.0
aldryn-search==0.2.10
certifi==2015.11.20.1
cmsplugin-filer==1.0.0
cmsplugin-forms-builder==1.0.1
dj-database-url==0.3.0
Django==1.8.7
django-admin-enhancer==1.0.0
django-admin-sortable==1.6.7
django-allauth==0.19.1
django-appconf==1.0.1
django-appdata==0.1.5
django-autocomplete-light==2.1.1
django-classy-tags==0.7.0
django-cms==3.1.4
django-colorful==1.0.1
django-compressor==1.6
django-contact-form==1.0
django-crispy-forms==1.4.0
django-disqus==0.5
django-easy-select2==1.3.1
django-email-extras==0.3.1
django-envelope==1.1
django-filer==1.0.4
django-forms-builder==0.12.2
django-formtools==1.0
django-generic-m2m==0.3.0
django-haystack==2.4.1
django-hvad==1.2.1
django-location-field==1.6.1
django-meta==0.3.1
django-meta-mixin==0.2.1
django-mptt==0.7.4
django-parler==1.5.1
django-polymorphic==0.7.2
django-reversion==1.8.7
django-secure==1.0.1
django-sekizai==0.9.0
Django-Select2==4.3.1
django-shop==0.2.0
django-sortedm2m==1.1.1
django-spurl==0.6.2
django-standard-form==1.1.1
django-taggit==0.17.6
django-taggit-autosuggest==0.2.8
django-taggit-templatetags==0.2.5
django-templatetag-sugar==1.0
django-treebeard==3.0
djangocms-admin-style==1.0.7
djangocms-apphook-setup==0.1.1
djangocms-blog==0.6.2
djangocms-column==1.5
djangocms-file==0.1
djangocms-flash==0.2.0
djangocms-googlemap==0.4.0
djangocms-inherit==0.1
djangocms-installer==0.7.3
djangocms-link==1.5
djangocms-picture==0.1
djangocms-slideshow==0.1.5
djangocms-snippet==1.4
djangocms-style==1.5
djangocms-teaser==0.1
djangocms-text-ckeditor==2.8.0
djangocms-video==0.1
djangocms-youtube==0.2.0
easy-thumbnails==2.3
ecdsa==0.13
Fabric==1.10.2
funcsigs==0.4
future==0.9.0
gunicorn==19.4.1
html5lib==0.9999999
isodate==0.5.4
jsonfield==1.0.3
Logentries==0.15
lxml==3.5.0
mock==1.3.0
oauthlib==1.0.3
opbeat==3.1.3
paramiko==1.16.0
pbr==1.8.1
Pillow==3.0.0
psycopg2==2.6.1
pycrypto==2.6.1
python-dateutil==2.4.2
python-gnupg==0.3.8
python-openid==2.2.5
pytz==2015.7
pyuploadcare==1.3.1
requests==2.8.1
requests-oauthlib==0.6.0
sendgrid==1.4.0
sendgrid-django==1.3.0
six==1.10.0
smtpapi==0.2.0
sphinx-me==0.3
Unidecode==0.4.18
URLObject==2.4.0
YURL==0.13
```

**Comment by yakky** [comment]
Could you check whether https://github.com/nephila/djangocms-blog/archive/develop.zip solves your issue?

**Comment by Zowie** [comment]
Thanks for the quick reply.

When I try it, the following happens:

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/zowielangdon/.virtualenvs/proj/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/zowielangdon/.virtualenvs/proj/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/Users/zowielangdon/.virtualenvs/proj/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/zowielangdon/.virtualenvs/proj/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/zowielangdon/.virtualenvs/proj/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/zowielangdon/Documents/vagrant/akoten/whia/project/proj/proj/proj_events/models/__init__.py", line 1, in <module>
    from .event import Event
  File "/Users/zowielangdon/Documents/vagrant/akoten/whia/project/proj/proj/proj_events/models/event.py", line 5, in <module>
    from proj_hotspots.models import Hotspot
  File "/Users/zowielangdon/Documents/vagrant/akoten/whia/project/proj/proj/proj_hotspots/models/__init__.py", line 1, in <module>
    from hotspot import Hotspot
  File "/Users/zowielangdon/Documents/vagrant/akoten/whia/project/proj/proj/proj_hotspots/models/hotspot.py", line 6, in <module>
    from djangocms_blog.models import Post
  File "/Users/zowielangdon/Documents/vagrant/akoten/packages/djangocms_blog/models.py", line 21, in <module>
    from .cms_appconfig import BlogConfig
  File "/Users/zowielangdon/Documents/vagrant/akoten/packages/djangocms_blog/cms_appconfig.py", line 15, in <module>
    class BlogConfig(TranslatableModel, AppHookConfig):
  File "/Users/zowielangdon/Documents/vagrant/akoten/packages/djangocms_blog/cms_appconfig.py", line 22, in BlogConfig
    _('object name'), max_length=234, default=get_setting('DEFAULT_OBJECT_NAME')
  File "/Users/zowielangdon/Documents/vagrant/akoten/packages/djangocms_blog/settings.py", line 62, in get_setting
    'BLOG_TYPES': meta_settings.OBJECT_TYPES,
AttributeError: 'module' object has no attribute 'OBJECT_TYPES'
```

Tried setting META_OBJECT_TYPES, but the error persists.

**Comment by Zowie** [comment]
Hi @yakky, might you have any idea how I can make this work anytime soon? :)

**Comment by yakky** [comment]
@Zowie is django-meta-mixin installed/added to INSTALLED_APPS? I can't reproduce this

**Comment by yakky** [comment]
Closing this to due lack of feedback
@Zowie  feel free to reopen if you have more details
