### ISSUE TITLE
Migration bug?

### ISSUE THREAD

**Issue by jsma** [nephila/djangocms-blog#305]
Just upgraded from 0.8 to 0.8.5 and am getting this error when running `./manage.py migrate`:

     ./manage.py migrate
    Traceback (most recent call last):
      File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "../lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
        utility.execute()
      File "../lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "../lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
        self.execute(*args, **cmd_options)
      File "../lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
        output = self.handle(*args, **options)
      File "../lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 89, in handle
        executor = MigrationExecutor(connection, self.migration_progress_callback)
      File "../lib/python3.5/site-packages/django/db/migrations/executor.py", line 20, in __init__
        self.loader = MigrationLoader(self.connection)
      File "../lib/python3.5/site-packages/django/db/migrations/loader.py", line 49, in __init__
        self.build_graph()
      File "../lib/python3.5/site-packages/django/db/migrations/loader.py", line 306, in build_graph
        _reraise_missing_dependency(migration, parent, e)
      File "../lib/python3.5/site-packages/django/db/migrations/loader.py", line 276, in _reraise_missing_dependency
        raise exc
      File "../lib/python3.5/site-packages/django/db/migrations/loader.py", line 302, in build_graph
        self.graph.add_dependency(migration, key, parent)
      File "../lib/python3.5/site-packages/django/db/migrations/graph.py", line 126, in add_dependency
        parent
    django.db.migrations.exceptions.NodeNotFoundError: Migration djangocms_blog.0018_thumbnail_move2 dependencies reference nonexistent parent node ('cmsplugin_filer_image', '0003_mv_thumbnail_option_to_filer_20160119_1720')

I'm running cmsplugin-filer==1.1.2 and that migration is there, so I'm not sure what's causing the dependency problem.

**Comment by jsma** [comment]
Oops, it helps if I delete the MIGRATION_MODULES setting after upgrading cmsplugin-filer :-/
Ignore me.
