### ISSUE TITLE
Dependencies of `migrations/0014_auto_20160215_1331.py` aren't complete

### ISSUE THREAD

**Issue by pywkm** [nephila/djangocms-blog#363]
Hi,
in our latest project we're using many of your djangocms plugins. Great work, thanks! 

However we recently encountered one tiny problem. After adding one of our app, we've suddenly started to get strange error when applying all migrations on empty database (project is still in development, so we drop database quite often). Error was strange, and nobody knew what was going on. 
We didn't notice at first that migrations suddenly started to apply in different order, and that was the reason why it started to crash. Normally it wouldn't be an issue, because Django can resolve dependencies if they are defined properly. Unfortunately IMO they are not properly defined in your `migrations/0014_auto_20160215_1331.py` file.

To explain why, let me show you log from applying migrations to our project before adding our last app:
```
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, cms, cmsplugin_filer_file, cmsplugin_filer_folder, cmsplugin_filer_image, contenttypes, djangocms_blog, djangocms_column, djangocms_googlemap, djangocms_highlightjs, djangocms_link, djangocms_page_meta, djangocms_redirect, djangocms_snippet, djangocms_style, djangocms_text_ckeditor, djangocms_video, easy_thumbnails, filer, menus, more_from_category, most_popular_posts, robots, sessions, sites, taggit
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying sites.0001_initial... OK
  Applying cms.0001_initial... OK
  Applying cms.0002_auto_20140816_1918... OK
  Applying cms.0003_auto_20140926_2347... OK
  Applying cms.0004_auto_20140924_1038... OK
  Applying cms.0005_auto_20140924_1039... OK
  Applying cms.0006_auto_20140924_1110... OK
  Applying cms.0007_auto_20141028_1559... OK
  Applying cms.0008_auto_20150208_2149... OK
  Applying cms.0008_auto_20150121_0059... OK
  Applying cms.0009_merge... OK
  Applying cms.0010_migrate_use_structure... OK
  Applying cms.0011_auto_20150419_1006... OK
  Applying cms.0012_auto_20150607_2207... OK
  Applying cms.0013_urlconfrevision... OK
  Applying cms.0014_auto_20160404_1908... OK
  Applying cms.0015_auto_20160421_0000... OK
  Applying cms.0016_auto_20160608_1535... OK
  Applying filer.0001_initial... OK
  Applying cmsplugin_filer_file.0001_initial... OK
  Applying cmsplugin_filer_file.0002_auto_20160112_1617... OK
  Applying cmsplugin_filer_file.0003_filerfile_link_attributes... OK
  Applying cmsplugin_filer_file.0004_auto_20160705_1334... OK
  Applying cmsplugin_filer_file.0005_auto_20160713_1853... OK
  Applying cmsplugin_filer_folder.0001_initial... OK
  Applying cmsplugin_filer_folder.0002_auto_20160113_1318... OK
  Applying cmsplugin_filer_folder.0003_auto_20160713_1853... OK
  Applying filer.0002_auto_20150606_2003... OK
  Applying filer.0003_thumbnailoption... OK
  Applying cmsplugin_filer_image.0001_initial... OK
  Applying cmsplugin_filer_image.0002_auto_20160108_1708... OK
  Applying cmsplugin_filer_image.0003_mv_thumbnail_option_to_filer_20160119_1720... OK
  Applying cmsplugin_filer_image.0004_auto_20160120_0950... OK
  Applying cmsplugin_filer_image.0005_auto_20160224_1457... OK
  Applying cmsplugin_filer_image.0006_auto_20160427_1438... OK
  Applying cmsplugin_filer_image.0007_filerimage_link_attributes... OK
  Applying cmsplugin_filer_image.0008_auto_20160705_1334... OK
  Applying cmsplugin_filer_image.0009_auto_20160713_1853... OK
  Applying taggit.0001_initial... OK
  Applying djangocms_blog.0001_initial... OK
  Applying djangocms_blog.0002_post_sites... OK
  Applying djangocms_blog.0003_auto_20141201_2252... OK
  Applying djangocms_blog.0004_auto_20150108_1435... OK
  Applying djangocms_blog.0005_auto_20150212_1118... OK
  Applying djangocms_blog.0006_auto_20150214_1907... OK
  Applying djangocms_blog.0007_auto_20150719_0933... OK
  Applying djangocms_blog.0008_auto_20150814_0831... OK
  Applying djangocms_blog.0009_latestpostsplugin_tags_new... OK
  Applying djangocms_blog.0010_auto_20150923_1151... OK
  Applying djangocms_blog.0011_auto_20151024_1809... OK
  Applying djangocms_blog.0012_auto_20151220_1734... OK
  Applying djangocms_blog.0013_auto_20160201_2235... OK
  Applying djangocms_blog.0014_auto_20160215_1331... OK
  Applying djangocms_blog.0015_auto_20160408_1849... OK
  Applying djangocms_blog.0016_auto_20160502_1741... OK
  Applying djangocms_blog.0017_thumbnail_move... OK
  Applying djangocms_blog.0018_thumbnail_move2... OK
  Applying djangocms_blog.0019_thumbnail_move3... OK
  Applying djangocms_blog.0020_thumbnail_move4... OK
  Applying djangocms_blog.0021_auto_20160823_2008... OK
  Applying djangocms_blog.0022_auto_20170304_1040... OK
  Applying djangocms_column.0001_initial... OK
  Applying djangocms_column.0002_auto_20160915_0818... OK
  [... more here, but irrelevant - all were applied to the last one]
```

And here is log/traceback from the same operation when there's one more migration to apply from our app (`authors`):
```
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, authors, cms, cmsplugin_filer_file, cmsplugin_filer_folder, cmsplugin_filer_image, contenttypes, djangocms_blog, djangocms_column, djangocms_googlemap, djangocms_highlightjs, djangocms_link, djangocms_page_meta, djangocms_redirect, djangocms_snippet, djangocms_style, djangocms_text_ckeditor, djangocms_video, easy_thumbnails, filer, menus, more_from_category, most_popular_posts, robots, sessions, sites, taggit
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying filer.0001_initial... OK
  Applying filer.0002_auto_20150606_2003... OK
  Applying filer.0003_thumbnailoption... OK
  Applying filer.0004_auto_20160328_1434... OK
  Applying filer.0005_auto_20160623_1425... OK
  Applying filer.0006_auto_20160623_1627... OK
  Applying filer.0007_auto_20161016_1055... OK
  Applying taggit.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying cms.0001_initial... OK
  Applying cms.0002_auto_20140816_1918... OK
  Applying cms.0003_auto_20140926_2347... OK
  Applying cmsplugin_filer_image.0001_initial... OK
  Applying cmsplugin_filer_image.0002_auto_20160108_1708... OK
  Applying cmsplugin_filer_image.0003_mv_thumbnail_option_to_filer_20160119_1720... OK
  Applying djangocms_blog.0001_initial... OK
  Applying djangocms_blog.0002_post_sites... OK
  Applying djangocms_blog.0003_auto_20141201_2252... OK
  Applying djangocms_blog.0004_auto_20150108_1435... OK
  Applying djangocms_blog.0005_auto_20150212_1118... OK
  Applying djangocms_blog.0006_auto_20150214_1907... OK
  Applying djangocms_blog.0007_auto_20150719_0933... OK
  Applying djangocms_blog.0008_auto_20150814_0831... OK
  Applying djangocms_blog.0009_latestpostsplugin_tags_new... OK
  Applying djangocms_blog.0010_auto_20150923_1151... OK
  Applying djangocms_blog.0011_auto_20151024_1809... OK
  Applying djangocms_blog.0012_auto_20151220_1734... OK
  Applying djangocms_blog.0013_auto_20160201_2235... OK
  Applying djangocms_blog.0014_auto_20160215_1331...Traceback (most recent call last):
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column cms_page.path does not exist
LINE 1: SELECT "cms_page"."id", "cms_page"."path", "cms_page"."depth...
                                ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 189, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/djangocms_blog/migrations/0014_auto_20160215_1331.py", line 18, in forwards
    for page in Page.objects.drafts().filter(application_urls='BlogApp'):
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __iter__
    self._fetch_all()
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/wiktor/venvs/project/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column cms_page.path does not exist
LINE 1: SELECT "cms_page"."id", "cms_page"."path", "cms_page"."depth...
                                ^
```

As you can see, main difference (and as I said, we didn't notice it at first - it cost us many hours of debugging :)) is that `cms` migrations load now only up to `0003` and jump to a different app. And when it comes to `djangocms_blog.0014_auto_20160215_1331` there's no column `cms_page.path` (which is created in `cms.0004_auto_20140924_1038` migration). Thats why we think, that dependencies in `djangocms_blog.0014_auto_20160215_1331` are incomplete. `cms.0004_auto_20140924_1038` should be added there, and as soon as I finish writing this report I will request a pull with quick fix of that file.

Needless to say, after applying that fix, log from loading migrations looks like that:
```
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, authors, cms, cmsplugin_filer_file, cmsplugin_filer_folder, cmsplugin_filer_image, contenttypes, djangocms_blog, djangocms_column, djangocms_googlemap, djangocms_highlightjs, djangocms_link, djangocms_page_meta, djangocms_redirect, djangocms_snippet, djangocms_style, djangocms_text_ckeditor, djangocms_video, easy_thumbnails, filer, menus, more_from_category, most_popular_posts, robots, sessions, sites, taggit
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying filer.0001_initial... OK
  Applying filer.0002_auto_20150606_2003... OK
  Applying filer.0003_thumbnailoption... OK
  Applying filer.0004_auto_20160328_1434... OK
  Applying filer.0005_auto_20160623_1425... OK
  Applying filer.0006_auto_20160623_1627... OK
  Applying filer.0007_auto_20161016_1055... OK
  Applying taggit.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying cms.0001_initial... OK
  Applying cms.0002_auto_20140816_1918... OK
  Applying cms.0003_auto_20140926_2347... OK
  Applying cmsplugin_filer_image.0001_initial... OK
  Applying cmsplugin_filer_image.0002_auto_20160108_1708... OK
  Applying cmsplugin_filer_image.0003_mv_thumbnail_option_to_filer_20160119_1720... OK
  Applying djangocms_blog.0001_initial... OK
  Applying djangocms_blog.0002_post_sites... OK
  Applying djangocms_blog.0003_auto_20141201_2252... OK
  Applying djangocms_blog.0004_auto_20150108_1435... OK
  Applying djangocms_blog.0005_auto_20150212_1118... OK
  Applying djangocms_blog.0006_auto_20150214_1907... OK
  Applying djangocms_blog.0007_auto_20150719_0933... OK
  Applying djangocms_blog.0008_auto_20150814_0831... OK
  Applying djangocms_blog.0009_latestpostsplugin_tags_new... OK
  Applying djangocms_blog.0010_auto_20150923_1151... OK
  Applying djangocms_blog.0011_auto_20151024_1809... OK
  Applying djangocms_blog.0012_auto_20151220_1734... OK
  Applying djangocms_blog.0013_auto_20160201_2235... OK
  Applying cms.0004_auto_20140924_1038... OK
  Applying djangocms_blog.0014_auto_20160215_1331... OK
  Applying djangocms_blog.0015_auto_20160408_1849... OK
  Applying djangocms_blog.0016_auto_20160502_1741... OK
  Applying djangocms_blog.0017_thumbnail_move... OK
  Applying djangocms_blog.0018_thumbnail_move2... OK
  Applying djangocms_blog.0019_thumbnail_move3... OK
  Applying djangocms_blog.0020_thumbnail_move4... OK
  Applying djangocms_blog.0021_auto_20160823_2008... OK
  Applying djangocms_blog.0022_auto_20170304_1040... OK
  Applying authors.0001_initial... OK
  Applying cms.0005_auto_20140924_1039... OK
  Applying cms.0006_auto_20140924_1110... OK
  Applying cms.0007_auto_20141028_1559... OK
  Applying cms.0008_auto_20150208_2149... OK
  Applying cms.0008_auto_20150121_0059... OK
  Applying cms.0009_merge... OK
  Applying cms.0010_migrate_use_structure... OK
  Applying cms.0011_auto_20150419_1006... OK
  Applying cms.0012_auto_20150607_2207... OK
  Applying cms.0013_urlconfrevision... OK
  Applying cms.0014_auto_20160404_1908... OK
  Applying cms.0015_auto_20160421_0000... OK
  Applying cms.0016_auto_20160608_1535... OK
  Applying cmsplugin_filer_file.0001_initial... OK
  Applying cmsplugin_filer_file.0002_auto_20160112_1617... OK
  [... more here, but also irrelevant - all goes well to the end :)]
```

We still don't know why order of migrations changed, and why just one random custom app can change it (and not two other added earlier). Maybe you know? I understand it's very random and rare if, for all those months, nobody reported you that kind of issue. :) It is also hard to reproduce, so I cannot give you exact instructions for it. That's why all I can show you is this set of three logs and many descriptions. :)
Anyway, I believe mentioned dependency should be updated if you don't want this issue to happen in future in somebody else project. :) What do you think?

Wiktor

**Comment by yakky** [comment]
Fixed by #364 , #365

Thanks @pywkm for reporting and fixing this!
