### ISSUE TITLE
CacheKey app_label & CMSPlugin fields.E300 installation errors

### ISSUE THREAD

**Issue by flooreeda** [nephila/djangocms-blog#367]
I'm having trouble installing djangocms-blog. I am following the instructions at http://djangocms-blog.readthedocs.io/en/latest/installation.html.

First, I got the following error when doing migrate:

> Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/diamonds/devel.thediamondapp.com/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/diamonds/devel.thediamondapp.com/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/diamonds/devel.thediamondapp.com/env/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/diamonds/devel.thediamondapp.com/env/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/diamonds/devel.thediamondapp.com/env/lib/python3.5/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/diamonds/devel.thediamondapp.com/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/diamonds/devel.thediamondapp.com/env/lib/python3.5/site-packages/cmsplugin_filer_image/models.py", line 12, in <module>
    from cms.models import CMSPlugin
  File "/home/diamonds/devel.thediamondapp.com/env/lib/python3.5/site-packages/cms/models/__init__.py", line 3, in <module>
    from .pagemodel import *  # nopyflakes
  File "/home/diamonds/devel.thediamondapp.com/env/lib/python3.5/site-packages/cms/models/pagemodel.py", line 24, in <module>
    from menus.menu_pool import menu_pool
  File "/home/diamonds/devel.thediamondapp.com/env/lib/python3.5/site-packages/menus/menu_pool.py", line 20, in <module>
    from menus.models import CacheKey
  File "/home/diamonds/devel.thediamondapp.com/env/lib/python3.5/site-packages/menus/models.py", line 30, in <module>
    class CacheKey(models.Model):
  File "/home/diamonds/devel.thediamondapp.com/env/lib/python3.5/site-packages/django/db/models/base.py", line 113, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class menus.models.CacheKey doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

After some searching, I got past this error by adding 'menus' to my INSTALLED_APPS which isn't part of the installation instructions.
But now, I get the following error when doing migrate: 

> SystemCheckError: System check identified some issues:
ERRORS:
cmsplugin_filer_image.FilerImage.cmsplugin_ptr: (fields.E300) Field defines a relation with model 'CMSPlugin', which is either not installed, or is abstract.
cmsplugin_filer_image.FilerImage.page_link: (fields.E300) Field defines a relation with model 'Page', which is either not installed, or is abstract.
djangocms_blog.AuthorEntriesPlugin.cmsplugin_ptr: (fields.E300) Field defines a relation with model 'CMSPlugin', which is either not installed, or is abstract.
djangocms_blog.GenericBlogPlugin.cmsplugin_ptr: (fields.E300) Field defines a relation with model 'CMSPlugin', which is either not installed, or is abstract.
djangocms_blog.LatestPostsPlugin.cmsplugin_ptr: (fields.E300) Field defines a relation with model 'CMSPlugin', which is either not installed, or is abstract.
djangocms_blog.Post.content: (fields.E300) Field defines a relation with model 'Placeholder', which is either not installed, or is abstract.

What could be the problem here?

**Comment by yakky** [comment]
@flooreeda django CMS blog instructions assumes a completely configured django CMS project. See http://django-cms.readthedocs.io/en/release-3.4.x/how_to/install.html for django CMS 3.4 installations instructions

**Comment by yakky** [comment]
Closings this. If installing / configuring django CMS does not fix the error, please feel free to reopen this
