### ISSUE TITLE
Keep getting these errors after following the installation steps

### ISSUE THREAD

**Issue by wilzha** [nephila/djangocms-blog#381]
Internal Server Error: /blog/
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/backends/django.py", line 68, in render
    reraise(exc, self.backend)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/backends/django.py", line 89, in reraise
    six.reraise(exc.__class__, new, sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/loader_tags.py", line 152, in render
    compiled_parent = self.get_parent(context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/loader_tags.py", line 149, in get_parent
    return self.find_template(parent, context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/loader_tags.py", line 129, in find_template
    template_name, skip=history,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/template/engine.py", line 146, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
TemplateDoesNotExist: INHERIT

![image](https://user-images.githubusercontent.com/1789954/27822506-64464dea-60d8-11e7-9741-d471065c8656.png)

**Comment by yakky** [comment]
@wilzha which version of Django, django CMS and djangocms-blog are you using?

**Comment by wilzha** [comment]
Django==1.10.5
django-cms==3.4.4
djangocms-blog==0.8.12

**Comment by yakky** [comment]
@wilzha is django CMS installed and working?
For some reason the "magic" ``INHERIT`` django CMS template is not recognised.

**Comment by yakky** [comment]
@wilzha have you made further tests?

**Comment by yakky** [comment]
@wilzha do you have any update on this?

**Comment by yakky** [comment]
@wilzha  if you want to talk about this in realtime, we just opened a gitter room https://gitter.im/nephila/applications
