### ISSUE TITLE
Table '<database>.djangocms_blog_latestpostsplugin_tags' doesn't exist when migrating

### ISSUE THREAD

**Issue by mikesdnielsen** [nephila/djangocms-blog#399]
Hello, 

I'm trying to migrate a djangocms site, that uses djangocms-blog from scratch. The site currently runs on MySQL and I'm working on moving to Postgresql. To do this, I've created an extra database setting for the Postgres database. My goal is to migrate the database layout, and then use dumpdata/loaddata to move it. 

```
./manage.py migrate --no-initial-data --database postgresql
```

I've also tried just the traditional way: 

```
./manage migrate --database postgresql
```

This gives the following error: 

```
  Applying djangocms_blog.0009_latestpostsplugin_tags_new...Traceback (most recent call last):
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/MySQLdb/connections.py", line 292, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1146, "Table 'database.djangocms_blog_latestpostsplugin_tags' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 183, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/djangocms_blog/migrations/0009_latestpostsplugin_tags_new.py", line 15, in migrate_tags
    for plugin in tag.latestpostsplugin_set.all():
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/Users/mike/virtualenvs/project/lib/python3.6/site-packages/MySQLdb/connections.py", line 292, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'database.djangocms_blog_latestpostsplugin_tags' doesn't exist")
```

Here are my database settings:

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'app_master',  # NOQA
        'USER': 'root',
        'PASSWORD': 'secret',
        'CON_MAX_AGE': 60,
    },
    'postgresql': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'app_dev',
        'USER': 'app_dev',
        'PASSWORD': 'secret',
        'HOST': 'localhost',
        'PORT': '',
    }
}
```

I'm running the following versions of packages: 
* Django 1.8.18
* django-cms 3.4.5
* djangocms-blog 0.8.12
* django-taggit 0.22.1

Any feedback on this would be appreciated :-)

**Comment by Postroutine** [comment]
Same problem here:

`python manage.py migrate`
Give me:
```
SystemCheckError: System check identified some issues:

ERRORS:
djangocms_blog.LatestPostsPlugin.tags: (fields.E300) Field defines a relation with model 'Tag', which is either not installed, or is abstract.
djangocms_blog.Post.tags: (fields.E300) Field defines a relation with model 'Tag', which is either not installed, or is abstract.
```

**Comment by yakky** [comment]
@Postroutine  is taggit in `INSTALLED_APPS`?
@mikesdnielsen have you setup the router to allow migration on `postgres` database too?
I your case (but I have not tested it) I suggest to proceed this way:
* run `dumpdata` (without arguments: you need to dump all the data at the same time)
* *replace* mysql database with postgres as the default
* run migrations with `--no-initial-data `
* load data back

This will allow you to skip the router and multidatabase configuration, which is not always easy

**Comment by mikesdnielsen** [comment]
@yakky Thanks for the reply! The issues I'm facing is that I've taken over this djangocms-based project and in several places they've overridden __new__ on classes and in this call, they're performing database look ups through the ORM. This seems to make a clean migration very difficult and I was hoping that doing it "side by side", I could work around this for now until I can refactor the __new__ functions.

I will try a few more things and get back with my findings - thank you again!

**Comment by yakky** [comment]
@mikesdnielsen did you successfully managed to migrate your dat?

**Comment by mikesdnielsen** [comment]
@yakky Yes, I managed to get this done in the end. The main issue was dumping everything together and that seemed to mess up. Dumping conttenttypes by itself and then the rest of the data actually worked without any changes :-)

**Comment by yakky** [comment]
@mikesdnielsen awesome, thanks for the update! :tada:
