### ISSUE TITLE
'CMSToolbar' object has no attribute 'edit_mode'

### ISSUE THREAD

**Issue by kiwiheretic** [nephila/djangocms-blog#483]
I am running Kubuntu 18.04 and have install fresh copy of Django CMS, install this blogging app and have run migrate.

My pip freeze is as follows:

(djangocms) djangocms $ pip freeze
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.                                                                                                                        
aldryn-apphooks-config==0.5.2
cmsplugin-filer==1.1.3
dj-database-url==0.5.0
Django==1.11.20
django-appconf==1.0.3
django-appdata==0.2.1
django-classy-tags==0.8.0
django-cms==3.6.0
django-filer==1.4.4
django-formtools==2.1
django-js-asset==1.2.2
django-meta==1.4.1
django-meta-mixin==0.3.0
django-mptt==0.9.1
django-parler==1.9.2
django-polymorphic==2.0.3
django-sekizai==0.10.0
django-sortedm2m==1.5.0
django-taggit==0.23.0
django-taggit-autosuggest==0.3.4
django-taggit-templatetags==0.2.5
django-templatetag-sugar==1.0
django-treebeard==4.3
djangocms-admin-style==1.2.9
djangocms-apphook-setup==0.3.0
djangocms-attributes-field==1.0.0
djangocms-blog==0.9.9
djangocms-column==1.9.0
djangocms-file==2.2.0
djangocms-googlemap==1.2.0
djangocms-installer==1.1.0
djangocms-link==2.3.1
djangocms-picture==2.0.8
djangocms-snippet==2.1.0
djangocms-style==2.1.0
djangocms-text-ckeditor==3.7.0
djangocms-video==2.0.5
easy-thumbnails==2.6
html5lib==1.0.1
lxml==4.3.2
Pillow==5.4.1
pytz==2018.9
six==1.12.0
tzlocal==1.5.1
Unidecode==1.0.23
webencodings==0.5.1
(djangocms) djangocms $ 

and the error occurs when just navigating to the home page.  

I did have a working djangocms install before this.

Here is a copy of my settings.py

(djangocms) djangocms $ cat djangocms/settings.py
import os  # isort:skip
gettext = lambda s: s
DATA_DIR = os.path.dirname(os.path.dirname(__file__))
"""
Django settings for djangocms project.

Generated by 'django-admin startproject' using Django 1.11.20.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j*d_^j8j1e$r2@h5yo2knyiy)q=01-jq@^ls^9!r%hfgh94tkj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

ROOT_URLCONF = 'djangocms.urls'

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Pacific/Auckland'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(DATA_DIR, 'media')
STATIC_ROOT = os.path.join(DATA_DIR, 'static')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'djangocms', 'static'),
)
SITE_ID = 1

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'djangocms', 'templates'),],
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.tz',
                'sekizai.context_processors.sekizai',
                'django.template.context_processors.static',
                'cms.context_processors.cms_settings'
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
                'django.template.loaders.eggs.Loader'
            ],
        },
    },
]

MIDDLEWARE = [
    'cms.middleware.utils.ApphookReloadMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware'
]

INSTALLED_APPS = [
    'djangocms_admin_style',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'cms',
    'menus',
    'sekizai',
    'treebeard',
    'djangocms_text_ckeditor',
    'filer',
    'easy_thumbnails',
    'djangocms_column',
    'djangocms_file',
    'djangocms_link',
    'djangocms_picture',
    'djangocms_style',
    'djangocms_snippet',
    'djangocms_googlemap',
    'djangocms_video',
    'djangocms',
    'aldryn_apphooks_config',
    'cmsplugin_filer_image',
    'parler',
    'taggit',
    'taggit_autosuggest',
    'meta',
    'sortedm2m',
    'djangocms_blog',
]

LANGUAGES = (
    ## Customize this
    ('en', gettext('en')),
)

CMS_LANGUAGES = {
    ## Customize this
    'default': {
        'public': True,
        'hide_untranslated': False,
        'redirect_on_fallback': True,
    },
    1: [
        {
            'public': True,
            'code': 'en',
            'hide_untranslated': False,
            'name': gettext('en'),
            'redirect_on_fallback': True,
        },
    ],
}

CMS_TEMPLATES = (
    ## Customize this
    ('fullwidth.html', 'Fullwidth'),
    ('sidebar_left.html', 'Sidebar Left'),
    ('sidebar_right.html', 'Sidebar Right')
)

CMS_PERMISSION = True

CMS_PLACEHOLDER_CONF = {}

DATABASES = {
    'default': {
        'CONN_MAX_AGE': 0,
        'ENGINE': 'django.db.backends.sqlite3',
        'HOST': 'localhost',
        'NAME': 'project.db',
        'PASSWORD': '',
        'PORT': '',
        'USER': ''
    }
}

MIGRATION_MODULES = {
    
}

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters'
)
META_SITE_PROTOCOL = 'http'
META_USE_SITES = True

#PARLER_LANGUAGES = {
#    1: (
#        {'code': 'en',},
#        {'code': 'it',},
#        {'code': 'fr',},
#    ),
#    'default': {
#        'fallbacks': ['en', 'it', 'fr'],
#    }
#}
(djangocms) $

complete traceback is

[16/Mar/2019 14:47:00] "GET / HTTP/1.1" 302 0
Internal Server Error: /en/
Traceback (most recent call last):
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/classytags/core.py", line 153, in render
    return self.render_tag(context, **kwargs)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/sekizai/templatetags/sekizai_tags.py", line 93, in render_tag
    rendered_contents = nodelist.render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/classytags/core.py", line 153, in render
    return self.render_tag(context, **kwargs)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/cms/templatetags/cms_tags.py", line 447, in render_tag
    return toolbar.render_with_structure(context, nodelist)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/cms/toolbar/toolbar.py", line 477, in render_with_structure
    rendered_contents = nodelist.render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/classytags/core.py", line 153, in render
    return self.render_tag(context, **kwargs)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/classytags/helpers.py", line 88, in render_tag
    flatten_context(self.get_context(context, **kwargs))
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/menus/templatetags/menu_tags.py", line 144, in get_context
    nodes = menu_renderer.get_nodes(namespace, root_id)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/utils/functional.py", line 115, in __wrapper__
    return getattr(res, method_name)(*args, **kw)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/menus/menu_pool.py", line 216, in get_nodes
    nodes = self._build_nodes()
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/menus/menu_pool.py", line 167, in _build_nodes
    nodes = menu.get_nodes(self.request)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/djangocms_blog/cms_menus.py", line 57, in get_nodes
    if not getattr(request, 'toolbar', False) or not request.toolbar.edit_mode:
AttributeError: 'CMSToolbar' object has no attribute 'edit_mode'
[16/Mar/2019 14:47:02] "GET /en/ HTTP/1.1" 500 214388
Internal Server Error: /en/
Traceback (most recent call last):
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/classytags/core.py", line 153, in render
    return self.render_tag(context, **kwargs)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/sekizai/templatetags/sekizai_tags.py", line 93, in render_tag
    rendered_contents = nodelist.render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/classytags/core.py", line 153, in render
    return self.render_tag(context, **kwargs)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/cms/templatetags/cms_tags.py", line 447, in render_tag
    return toolbar.render_with_structure(context, nodelist)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/cms/toolbar/toolbar.py", line 477, in render_with_structure
    rendered_contents = nodelist.render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/classytags/core.py", line 153, in render
    return self.render_tag(context, **kwargs)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/classytags/helpers.py", line 88, in render_tag
    flatten_context(self.get_context(context, **kwargs))
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/menus/templatetags/menu_tags.py", line 144, in get_context
    nodes = menu_renderer.get_nodes(namespace, root_id)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/django/utils/functional.py", line 115, in __wrapper__
    return getattr(res, method_name)(*args, **kw)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/menus/menu_pool.py", line 216, in get_nodes
    nodes = self._build_nodes()
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/menus/menu_pool.py", line 167, in _build_nodes
    nodes = menu.get_nodes(self.request)
  File "/home/glenn/venvs/djangocms/local/lib/python2.7/site-packages/djangocms_blog/cms_menus.py", line 57, in get_nodes
    if not getattr(request, 'toolbar', False) or not request.toolbar.edit_mode:
AttributeError: 'CMSToolbar' object has no attribute 'edit_mode'
[16/Mar/2019 14:47:03] "GET /en/ HTTP/1.1" 500 214260

Any thoughts?

**Comment by yakky** [comment]
@kiwiheretic thanks for reporting this.
djangocms-blog < 1.0 supports up to django CMS 3.5.x
django CMS 3.6 support is provided by djangocms-blog 1.0b1 which is available on PyPi (`pip install djangocms-blog==1.0b1`), we hope to release a stable version soon!

**Comment by yakky** [comment]
Closing this as fixed in develop / 1.0b1

Thanks for the report
