### ISSUE TITLE
Deleting auto-generated cms_appconfig breaks site: BlogConfig matching query does not exist.

### ISSUE THREAD

**Issue by tehfink** [nephila/djangocms-blog#495]
On a fresh install of:
- django-cms==3.6.0
- Django==1.11.22
- djangocms-blog==1.0.0b1 ([search] & [taggit])

Steps to reproduce:
- After installing djangocms-blog, run migrations
- Create a new page, and there also a new BlogConfig with custom values, attaching the app as an apphook
- Delete the existing default BlogConfig, so that users don't have to choose a config when creating a new Blog entry
- Create some Blog entries, all using only the new BlogConfig
- Restart development server

Result: navigating to any page (starting with the root page) gives this error:
```python
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/classytags/core.py", line 153, in render
    return self.render_tag(context, **kwargs)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/sekizai/templatetags/sekizai_tags.py", line 89, in render_tag
    rendered_contents = nodelist.render(context)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/classytags/core.py", line 153, in render
    return self.render_tag(context, **kwargs)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/cms/templatetags/cms_tags.py", line 447, in render_tag
    return toolbar.render_with_structure(context, nodelist)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/cms/toolbar/toolbar.py", line 477, in render_with_structure
    rendered_contents = nodelist.render(context)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/template/loader_tags.py", line 216, in render
    return template.render(context)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/classytags/core.py", line 153, in render
    return self.render_tag(context, **kwargs)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/classytags/helpers.py", line 88, in render_tag
    flatten_context(self.get_context(context, **kwargs))
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/menus/templatetags/menu_tags.py", line 144, in get_context
    nodes = menu_renderer.get_nodes(namespace, root_id)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/utils/functional.py", line 115, in __wrapper__
    return getattr(res, method_name)(*args, **kw)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/menus/menu_pool.py", line 216, in get_nodes
    nodes = self._build_nodes()
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/menus/menu_pool.py", line 167, in _build_nodes
    nodes = menu.get_nodes(self.request)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/djangocms_blog/cms_menus.py", line 51, in get_nodes
    namespace=self.instance.application_namespace
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
djangocms_blog.cms_appconfig.DoesNotExist: BlogConfig matching query does not exist.
```

**Comment by yakky** [comment]
Have you deleted the auto created blog page?

**Comment by tehfink** [comment]
Thanks for the reply. Yes, I had deleted the auto-created blog page.

The rabbit hole continues: I disabled the apphook on the new "News" page, in an attempt to troubleshoot, then republished the page. This allows the other pages to load. However, now the Blog app section does not appear in the admin, nor is it available as an apphook.
This error appears on restart of the dev server: `…site-packages/cms/apphook_pool.py:98: UserWarning: No registered apphook "'BlogApp'" found warnings.warn(_('No registered apphook "%r" found') % app_name)`

**Comment by yakky** [comment]
@tehfink can you try clearing the django cache? It might be the django cms menu cache which still tries to render the old page in the menu

**Comment by tehfink** [comment]
I ran in the django shell:
```python
from django.core.cache import cache
cache.clear()
```
and: `find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf` in the virtualenv.

Unfortunately it gave the same result: `No registered apphook "'BlogApp'" found`, and the app does not appear in the Django admin.

How could I troubleshoot?

**Comment by yakky** [comment]
@tehfink can you try running:

```
from menus.menu_pool import menu_pool
menu_pool.clear(all=True)
```

I have opened #497 which should fix the issue on from now on

**Comment by tehfink** [comment]
@yakky Thanks for the help. Unfortunately running that command hasn't helped: the error is the same as above, the app does not appear in the Django admin.

Could I delete this reference manually?

**Comment by yakky** [comment]
@tehfink
the current database status is that you have 1 non default `BlogConfig` instance, with its categories and posts, but it's not attached to a page, and the blog admin does not appear anymore right?
1) what's the result of `select * from cms_page where application_urls='BlogApp';`?
2) what's the result of `select * from djangocms_blog_blogconfig`?
3) could you post the full updated traceback?
I'm quite puzzled by the disappearance of the app from the admin. that should never be the case :thinking:

**Comment by tehfink** [comment]
@yakky Thanks very much for the help!

> the current database status is that you have 1 non default BlogConfig instance, with its categories and posts, but it's not attached to a page, and the blog admin does not appear anymore right?

Correct. And even if I wanted to attach the blog app to a page, it no longer appeared in the page's apphook dropdown menu.

```sql
sqlite> select * from cms_page where application_urls='BlogApp';
131|script|script|2019-07-28 17:57:55.224453|2019-07-28 17:57:55.333470|2019-07-28 17:57:55.279529||1|0|||home.html|0||0|BlogApp|Blog|1|en|0|0|67|132
132|script|script|2019-07-28 17:57:55.279710|2019-07-28 17:57:55.341196|2019-07-28 17:57:55.279529||1|0|||home.html|0||0|BlogApp|Blog|0|en|0|0|67|131
sqlite> select * from djangocms_blog_blogconfig;
2|amc NewsBlog|{"config": {"default_published": false, "default_image_full": null, "default_image_thumbnail": null, "url_patterns": "full_date", "use_placeholder": true, "use_abstract": true, "use_related": true, "set_author": false, "paginate_by": "10", "template_prefix": "", "menu_structure": "posts", "menu_empty_categories": false, "sitemap_changefreq": "monthly", "sitemap_priority": "0.5", "object_type": "Article", "og_type": "Article", "og_app_id": "", "og_profile_id": "", "og_publisher": "", "og_author_url": "get_author_url", "og_author": "get_author_name", "twitter_type": "summary", "twitter_site": "", "twitter_author": "get_author_twitter", "gplus_type": "Blog", "gplus_author": "get_author_gplus", "send_knock_create": false, "send_knock_update": false}}|djangocms_blog.cms_appconfig.BlogConfig
```

Unfortunately (for debugging), no traceback was displayed anymore. The only message shown was during startup of the development server or console:
```python
$ python manage.py runserver_plus
/Users/tehfink/Documents/Code/…/virtualenv/lib/python3.6/site-packages/cms/apphook_pool.py:98: UserWarning: No registered apphook "'BlogApp'" found
  warnings.warn(_('No registered apphook "%r" found') % app_name)
System check identified some issues:

 * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
 * Restarting with stat
Performing system checks...
```

Based on the sql result above, I found and deleted page 131, cleared the menu cache, then rebuilt the virtualenv (which may have been overkill, but also effective). Now the blog app shows in the admin, and I was able to apphook it to a page.
Thanks again!

**Comment by yakky** [comment]
@tehfink awesome, thanks for the update. I will release 0.9.11 with the automatic menu cache purge on `BlogConfig` delete, which I think could have prevented your issue completely. thanks for the debugging and the information :+1:
