### ISSUE TITLE
django 1.8 and python 3 ready?

### ISSUE THREAD

**Issue by jedie** [nephila/djangocms-blog#78]
Is djangocms-blog django 1.8 ready?

And what's about python 3?

**Comment by yakky** [comment]
django CMS it's still not ported to 1.8 (mostly because django CMS itself is not Django 1.8 ready)
It's Python 3 compatible using `django-select2-py3` instead of `django-select2` (but the setup.py will take care of using the right dependency)

**Comment by jedie** [comment]
Thanks for the info!

**Comment by jedie** [comment]
I tried a installation with python 3.4:
```
$ pip install djangocms-blog --verbose
...
    Skipping link https://github.com/applegrew/django-select2/issues/8 (from https://pypi.python.org/simple/django-select2/); not a file
    Skipping link https://www.djangoproject.com/ (from https://pypi.python.org/simple/django-select2/); not a file
  Using version 4.2.2 (newest of versions: 4.2.2, 4.2.1, 4.2.0, 4.0.0, 3.3.1, 3.3.0, 3.2.1, 3.2.0, 3.1.5, 3.1.4, 3.1.3, 3.1.2, 3.1.1, 3.1.0, 3.0.2, 3.0.1, 3.0, 2.0.1)
  Using cached Django-Select2-4.2.2.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/D/Django-Select2/Django-Select2-4.2.2.tar.gz#md5=2733623861da1bfe9837069c2121a239 (from https://pypi.python.org/simple/django-select2/)
  Running setup.py (path:/tmp/pip-build-crwnwa0q/django-select2/setup.py) egg_info for package django-select2
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 20, in <module
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module
    
    ----------------------------------------
    Cleaning up...
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-crwnwa0q/django-select2
    Exception information:
    Traceback (most recent call last):
      File "/home/jens/PyLucid_env/lib/python3.4/site-packages/pip/basecommand.py", line 232, in main
        status = self.run(options, args)
      File "/home/jens/PyLucid_env/lib/python3.4/site-packages/pip/commands/install.py", line 339, in run
        requirement_set.prepare_files(finder)
      File "/home/jens/PyLucid_env/lib/python3.4/site-packages/pip/req/req_set.py", line 385, in prepare_files
        req_to_install.run_egg_info()
      File "/home/jens/PyLucid_env/lib/python3.4/site-packages/pip/req/req_install.py", line 358, in run_egg_info
        command_desc='python setup.py egg_info')
      File "/home/jens/PyLucid_env/lib/python3.4/site-packages/pip/utils/__init__.py", line 749, in call_subprocess
        % (command_desc, proc.returncode, cwd))
    pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-crwnwa0q/django-select2
```

Seems that the wrong version will be choose.

**Comment by yakky** [comment]
Apparently the wheel package can't resolve the dependency correctly
` pip install djangocms-blog --no-use-wheel` should allow a clean install

Reopening this to track the issue and find a way to solve it

**Comment by jedie** [comment]
I think, remove the **install_requires=[]** and document a **pip install -r djangocms-blog-requirements.txt** call as a prefix command.

**Comment by yakky** [comment]
Testing a solution which implements PEP426, will issue an alpha version soon to PyPi

**Comment by yakky** [comment]
Would you try 0.3.2.a1? `pip install djangocms-blog==0.3.2.a1`

**Comment by jedie** [comment]
I have uninstall djangocms-blog and django-select2-py3
seems to work:
```
$ pip install djangocms-blog==0.3.2.a1
Collecting djangocms-blog==0.3.2.a1
  Downloading djangocms_blog-0.3.2.a1-py2.py3-none-any.whl (82kB)
    100% |################################| 86kB 320kB/s 
Requirement already satisfied (use --upgrade to upgrade): pytz in /home/jens/PyLucid_env/lib/python3.4/site-packages (from djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): django-filer in /home/jens/PyLucid_env/lib/python3.4/site-packages (from djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): django-taggit-autosuggest in /home/jens/PyLucid_env/lib/python3.4/site-packages (from djangocms-blog==0.3.2.a1)
Collecting django-select2-py3 (from djangocms-blog==0.3.2.a1)
  Using cached Django-Select2-Py3-4.2.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): django-taggit-templatetags in /home/jens/PyLucid_env/lib/python3.4/site-packages (from djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): djangocms-text-ckeditor in /home/jens/PyLucid_env/lib/python3.4/site-packages (from djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): django-taggit in /home/jens/PyLucid_env/lib/python3.4/site-packages (from djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): django-meta-mixin>=0.1.1 in /home/jens/PyLucid_env/lib/python3.4/site-packages (from djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): django-cms>=3.0 in /home/jens/PyLucid_env/lib/python3.4/site-packages (from djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): cmsplugin-filer in /home/jens/PyLucid_env/lib/python3.4/site-packages (from djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): south>=1.0.1 in /home/jens/PyLucid_env/lib/python3.4/site-packages (from djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): django-meta>=0.2 in /home/jens/PyLucid_env/lib/python3.4/site-packages (from djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): django-parler>=1.2 in /home/jens/PyLucid_env/lib/python3.4/site-packages (from djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): django-admin-enhancer in /home/jens/PyLucid_env/lib/python3.4/site-packages (from djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): Django>=1.4 in /home/jens/PyLucid_env/lib/python3.4/site-packages (from django-filer->djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): easy-thumbnails>=1.0 in /home/jens/PyLucid_env/lib/python3.4/site-packages (from django-filer->djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): django-mptt<0.6.2,>=0.6 in /home/jens/PyLucid_env/lib/python3.4/site-packages (from django-filer->djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): django-polymorphic>=0.2 in /home/jens/PyLucid_env/lib/python3.4/site-packages (from django-filer->djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): Unidecode>=0.04 in /home/jens/PyLucid_env/lib/python3.4/site-packages (from django-filer->djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): django-templatetag-sugar>=0.1 in /home/jens/PyLucid_env/lib/python3.4/site-packages (from django-taggit-templatetags->djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): html5lib in /home/jens/PyLucid_env/lib/python3.4/site-packages (from djangocms-text-ckeditor->djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): Pillow in /home/jens/PyLucid_env/lib/python3.4/site-packages (from djangocms-text-ckeditor->djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): django-sekizai in /home/jens/PyLucid_env/lib/python3.4/site-packages (from django-meta-mixin>=0.1.1->djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): djangocms-admin-style in /home/jens/PyLucid_env/lib/python3.4/site-packages (from django-cms>=3.0->djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): django-classy-tags>=0.5 in /home/jens/PyLucid_env/lib/python3.4/site-packages (from django-cms>=3.0->djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): django-appconf in /home/jens/PyLucid_env/lib/python3.4/site-packages (from cmsplugin-filer->djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/jens/PyLucid_env/lib/python3.4/site-packages (from django-polymorphic>=0.2->django-filer->djangocms-blog==0.3.2.a1)
Requirement already satisfied (use --upgrade to upgrade): six in /home/jens/PyLucid_env/lib/python3.4/site-packages (from html5lib->djangocms-text-ckeditor->djangocms-blog==0.3.2.a1)
Installing collected packages: django-select2-py3, djangocms-blog
  Running setup.py install for django-select2-py3

Successfully installed django-select2-py3-4.2.1 djangocms-blog-0.3.2a1
```

**Comment by yakky** [comment]
\o/

**Comment by jedie** [comment]
This can be closed, isn't it?

**Comment by yakky** [comment]
Yes, thanks
