### ISSUE TITLE
install on djangocms 4.1

### ISSUE THREAD

**Issue by pooria-ghorbani** [nephila/djangocms-blog#788]
when run migrate return this error : 
''''
Traceback (most recent call last):
  File "/home/master/wisiweb/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "djangocms_blog_blogconfig" does not exist
LINE 1: ...ace", "djangocms_blog_blogconfig"."app_data" FROM "djangocms...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/master/wisiweb/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/master/wisiweb/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/home/master/wisiweb/.venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/master/wisiweb/.venv/lib/python3.8/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/home/master/wisiweb/.venv/lib/python3.8/site-packages/cms/apps.py", line 13, in ready
    setup_cms_apps()
  File "/home/master/wisiweb/.venv/lib/python3.8/site-packages/cms/utils/setup.py", line 62, in setup_cms_apps
    backwards_compatibility_config()
  File "/home/master/wisiweb/.venv/lib/python3.8/site-packages/cms/app_registration.py", line 169, in backwards_compatibility_config
    import_module('%s.%s' % (app_config.name, module))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/master/wisiweb/.venv/lib/python3.8/site-packages/djangocms_blog/cms_wizards.py", line 100, in <module>
    for config in BlogConfig.objects.all().order_by("namespace"):
  File "/home/master/wisiweb/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/home/master/wisiweb/.venv/lib/python3.8/site-packages/parler/managers.py", line 42, in _fetch_all
    super()._fetch_all()
  File "/home/master/wisiweb/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/master/wisiweb/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/master/wisiweb/.venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/master/wisiweb/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/home/master/wisiweb/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/home/master/wisiweb/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/master/wisiweb/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/home/master/wisiweb/.venv/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/master/wisiweb/.venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "djangocms_blog_blogconfig" does not exist
LINE 1: ...ace", "djangocms_blog_blogconfig"."app_data" FROM "djangocms...
''''

**Comment by protoroto** [comment]
@pooria-ghorbani Hi! Thanks for reporting this. Unfortunately djangocms-blog is not ready for Django CMS 4.1: we're working on making it compatible, but as of now you have to stick to Django CMS 3.11 if using djangocms-blog

**Comment by pooria-ghorbani** [comment]
my project on djangocms 4.1 , i can not return to 3.11 , also i need to djangocms-blog for my project in cms 4.1

**Comment by protoroto** [comment]
@pooria-ghorbani I understand, but right now ther's no compatibility between djangocms-blog and Django CMS 4.1: because 4.1 changes are quite big, it will not be an easy task.

**Comment by trsh** [comment]
@protoroto any eta, on when it could happen? Aprox?

**Comment by protoroto** [comment]
@trsh Hi! We're working  on it: sadly I can't give you any eta but development is active! A lot of work is already done, and we'll try to put all pieces together as soon as possible

**Comment by fdik** [comment]
Hi, on which branch are you working on it? Then I could use this one until a release arrives. We're setting up a new site and I don't want to do this with an outdated version. Thanks.

**Comment by fsbraun** [comment]
@fdik I have a fork here: https://github.com/fsbraun/djangocms-blog/tree/develop-4  
Let me know any feedback!

**Comment by fdik** [comment]
Thanks! I'll give it a try. Because I'm new to django-cms, is djangocms-blog a common django app or are there any special things to know to install? And if so where can I find documentation?

**Comment by arjan-s** [comment]
Hi, is there any news on this?

**Comment by fsbraun** [comment]
The Django CMS 4+ version has been forked from this repo: http://github.com/django-cms/djangocms-stories
