### ISSUE TITLE
Error at root url without trailing slash

### ISSUE THREAD

**Issue by palmitoto** [nephila/djangocms-blog#793]
## Description

When I go to the blog root page without the trailing slash, I get an Internal Server Error.

## Steps to reproduce

Go to the blog root url without the / at the end.

## Versions

Python 3.11
Django 4.2.10
django-cms-blog 2
django-cms 3.11

## Expected behavior

Redirect to /fr/blog/

## Actual behaviour

I get an Internal Server Error : 

Report at /fr/blog
Internal Server Error: /fr/blog
Traceback (most recent call last): None

## Additional information

I don't have this problem for an article url. 
I also don't have the problem if I switch back to Django 3.2.
I also don't have the problem if debug=True
APPENS_SLASH settings are set to True

**Comment by protoroto** [comment]
@palmitoto Hi! Thanks for reporting this! Do you have some sort of traceback of the error? I can't reproduce it (for example, here https://www.nephila.digital/en/blog , ther's a blog instance of DjangoCMS Blog).

**Comment by palmitoto** [comment]
Hi, thanks for your time!

This my stack : 

```
Resolver404: {'tried': [[<URLResolver <module 'loginas.urls' from '/home/kapt/workspace/my_project/.venv/lib/python3.11/site-packages/loginas/urls.py'> (None:None) 'kapt/'>], [<URLResolver <URLPattern list> (admin:admin) 'kapt/'>], [<URLResolver <module 'django_select2.urls' from '/home/kapt/workspace/my_project/.venv/lib/python3.11/site-packages/django_select2/urls.py'> (django_select2:django_select2) 'select2/'>], [<URLResolver <module 'libs.emails.test.urls' from '/home/kapt/workspace/my_project/src/libs/emails/test/urls.py'> (None:None) 'test-mail/'>], [<URLResolver <module 'cookie_optin.urls' from '/home/kapt/workspace/my_project/.venv/lib/python3.11/site-packages/cookie_optin/urls.py'> (cookie_optin:cookie_optin) 'cookie-optin/'>], [<URLResolver <module 'taggit_autosuggest.urls' from '/home/kapt/workspace/my_project/.venv/lib/python3.11/site-packages/taggit_autosuggest/urls.py'> (None:None) 'taggit_autosuggest/'>], [<URLResolver <module 'fobi.urls.view' from '/home/kapt/workspace/my_project/.venv/lib/python3.11/site-packages/fobi/urls/v...
  File "django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 181, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "django/core/handlers/base.py", line 313, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "django/urls/resolvers.py", line 702, in resolve
    raise Resolver404({"tried": tried, "path": new_path})
Resolver404: {'tried': [[<URLResolver <module 'loginas.urls' from '/home/kapt/workspace/my_project/.venv/lib/python3.11/site-packages/loginas/urls.py'> (None:None) 'kapt/'>], [<URLResolver <URLPattern list> (admin:admin) 'kapt/'>], [<URLResolver <module 'django_select2.urls' from '/home/kapt/workspace/my_project/.venv/lib/python3.11/site-packages/django_select2/urls.py'> (django_select2:django_select2) 'select2/'>], [<URLResolver <module 'libs.emails.test.urls' from '/home/kapt/workspace/my_project/src/libs/emails/test/urls.py'> (None:None) 'test-mail/'>], [<URLResolver <module 'cookie_optin.urls' from '/home/kapt/workspace/my_project/.venv/lib/python3.11/site-packages/cookie_optin/urls.py'> (cookie_optin:cookie_optin) 'cookie-optin/'>], [<URLResolver <module 'taggit_autosuggest.urls' from '/home/kapt/workspace/my_project/.venv/lib/python3.11/site-packages/taggit_autosuggest/urls.py'> (None:None) 'taggit_autosuggest/'>], [<URLResolver <module 'fobi.urls.view' from '/home/kapt/workspace/my_project/.venv/lib/python3.11/site-packages/fobi/urls/v...
  File "django/core/handlers/exception.py", line 164, in get_exception_response
    response = callback(request, exception=exception)
  File "django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "django/views/defaults.py", line 64, in page_not_found
    body = template.render(context, request)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 175, in render
    return self._render(context)
  File "django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "classytags/core.py", line 142, in render
    return str(self.render_tag(context, **kwargs))
  File "sekizai/templatetags/sekizai_tags.py", line 87, in render_tag
    rendered_contents = nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "classytags/core.py", line 142, in render
    return str(self.render_tag(context, **kwargs))
  File "cms/templatetags/cms_tags.py", line 433, in render_tag
    return nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 208, in render
    return template.render(context)
  File "django/template/base.py", line 177, in render
    return self._render(context)
  File "django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "django/template/defaulttags.py", line 541, in render
    return self.nodelist.render(context)
  File "django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "classytags/core.py", line 142, in render
    return str(self.render_tag(context, **kwargs))
  File "classytags/helpers.py", line 88, in render_tag
    flatten_context(self.get_context(context, **kwargs))
  File "menus/templatetags/menu_tags.py", line 141, in get_context
    nodes = menu_renderer.get_nodes(namespace, root_id)
  File "django/utils/functional.py", line 150, in __wrapper__
    return getattr(res, method_name)(*args, **kw)
  File "menus/menu_pool.py", line 234, in get_nodes
    nodes = self.apply_modifiers(
  File "menus/menu_pool.py", line 228, in apply_modifiers
    nodes = inst.modify(
  File "djangocms_blog/cms_menus.py", line 185, in modify
    namespace = resolve(request.path).namespace
  File "django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "django/urls/resolvers.py", line 702, in resolve
    raise Resolver404({"tried": tried, "path": new_path})
```

**Comment by protoroto** [comment]
This is strange: do you have `"django.middleware.common.CommonMiddleware"` in your project `MIDDLEWARE` settings?

**Comment by palmitoto** [comment]
Yes:

```
MIDDLEWARE = (
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.http.ConditionalGetMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.contrib.sites.middleware.CurrentSiteMiddleware",
)

**Comment by protoroto** [comment]
Do you have some custom context processor trying to resolve urls? Because in any case this should throw a 500 error: it should throw a 404 if it can't resolve urls. Are you able to reproduce this with a fresh djangocms 3.11 and djangocms-blog installation?

**Comment by palmitoto** [comment]
On a fresh install from django-cms boilerplate, i get a 404. So I will compare with my settings to find the error.

How do you handle this case  (404) on nephila blog? Put a redirection ?

**Comment by protoroto** [comment]
On nephila blog, both urls works correctly (with or without trailing slash). This should be the case for ALL urls, given that the urlconf is done correctly. In this case the Blog apphook, attached to the page, should leverage all the work, unless I'm missing some configuration that I don't know. 
I'm sorry I can't be of more help here :(

**Comment by palmitoto** [comment]
Thank @protoroto  for all the time spent, which has already helped me move forward.

**Comment by febsn** [comment]
@palmitoto have you been able to resolve this? I'm facing the same issue after upgrading to Django 4.2, and only getting `Traceback: None`.

**Comment by febsn** [comment]
I've come a little closer. My 404 template used the `menu_tags` library to display navigation. When I remove it (and the corresponding tags) the redirect works. Seems like the 404 is raised at a stage where, for some reason, it can't use navigation tags from the cms, and django tries some template rendering before the 404 is caught by `CommonMiddleware` (somewhere around https://github.com/django/django/blob/6f9fea33137fee6416ff43b775aa9567440a23d3/django/middleware/common.py#L69).

I'm still not sure how to resolve this, since a 404 without navigation isn't of much use. Any detailed ideas what's going here?

**Comment by palmitoto** [comment]
The error was very isolated I did not look further. But recently on a new site we had the same error and the "solution" was to remove the menus from the 404 page...

**Comment by febsn** [comment]
I've just encountered the same problem with another (custom-built) apphook. So I'd assume it's not djangocms-blog. I'm going to file an issue in django-cms when I have time (but please go ahead if you'd like to).

**Comment by milkomeda** [comment]
We also see the same problem after a recent upgrade to Django 4.2 with multiple websites using djangocms-blog. All affected websites use `show_menu` in 404.html  template.

I tracked down the error happening in `class BlogNavModifier` of djangocms-blog `cms_menus.py`.

`namespace = resolve(request.path).namespace` fails as it results without trailing slash in `django.urls.exceptions.Resolver404`.

see https://github.com/nephila/djangocms-blog/blob/3f6d89321939530e49c81f497d503c8290cb30c7/djangocms_blog/cms_menus.py#L151

While `DEBUG = False` results in an Internal Server Error without traceback, `DEBUG = True` results in the expected redirect (including trailing slash).

Any help would be much appreciated.

**Comment by fsbraun** [comment]
Oh, wow, @milkomeda ! I've been struggling for a while now with this issue.

It seems that the Common Middleware first renders the 404 page before turning the rendered result into a redirect to the site with the slash. This leads the cms_menus to fail (as you noticed). 

Nephila's page works since it has no navigation on its 404 page...

I see two solutions:

* Put a try-except around 151 and let the middleware do its bit.
* Catch a Resolver404 and try again with slash (should it be missing)

**Comment by fsbraun** [comment]
@protoroto This commit solved the problem for my fork: https://github.com/fsbraun/djangocms-blog/commit/6de1f58eaea6ba480f15abb1da9a5f0ab9d9ba77

**Comment by protoroto** [comment]
@fsbraun Thanks :) I'll try to have a look at it as soon as possible!

**Comment by protoroto** [comment]
@fsbraun @milkomeda Just for information, this happens with Django 4.2 only, right? Django 3.2 is not affected?

**Comment by fsbraun** [comment]
@protoroto As far as I can see, you are right: The common middleware changed after 3.2. In 3.2 the redirect was issued **before** processing the request, as of 4.2 (latest) it is issued **after** processing the request.

**Comment by milkomeda** [comment]
Hi @protoroto, is there a schedule for when the new version will be released? We receive hundreds of errors from several projects from our monitoring on a daily basis because of this. These errors are shadowing real errors in the meantime.

If you are not able to release a bug fix, please give me a sign and we try to monkey patch around it.

**Comment by protoroto** [comment]
@milkomeda Sorry for the delay: I'll try to wrap everything up at the beginning of next week.

**Comment by milkomeda** [comment]
Hi @protoroto any chance to get this small bug fix released soon? please 🙏 

Is there anything I can help with? We are still receiving a lot of error mails because of this change in common middleware between Django 3.2 and 4.2.

**Comment by protoroto** [comment]
@milkomeda Sorry for the late answer: I've just merged a pr with @fsbraun fix, should release a new version tomorrow.

**Comment by protoroto** [comment]
@milkomeda I've just release version 2.0.9 with this fix: could you please try and tell me if this error goes away?

**Comment by milkomeda** [comment]
@protoroto Just tested this for one production vhost and can confirm that this release fixes our issue. Deployment for all vhosts is running. 👍 🙏

**Comment by palmitoto** [comment]
This release fix myu problem too ! Thank you for all

**Comment by protoroto** [comment]
@palmitoto @milkomeda Thanks for the feedback, I'll close this issue then.
